apiVersion: apps/v1
kind: Deployment
metadata:
  name: proyecto-final-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proyecto-final-app
  template:
    metadata:
      labels:
        app: proyecto-final-app
    spec:
      containers:
      - name: app
        image: kevmev/proyecto-final-app:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: proyecto-final-app-service
spec:
  selector:
    app: proyecto-final-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30000
  type: NodePort
